spring.application.name=Prisma
spring.devtools.restart.enabled=true
spring.datasource.url=jdbc:oracle:thin:${OracleDB_NAME}?TNS_ADMIN=${OracleDBPath}
spring.datasource.username=${OracleDBUser}
spring.datasource.password=${OracleDBPW}

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.show-sql=true